# Generated by Django 4.2.11 on 2024-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_id_user_address_user_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(max_length=50),
        ),
    ]
